
export const DEFAULT_DECK_SETTINGS = {
  newCardsPerDay: 20,
  reviewLimitPerDay: 100,
  learningSteps: [1, 10], // minutes
  graduatingInterval: 1, // days
  easyInterval: 4, // days
  startingEase: 2.5,
};

export const AR = {
  appName: "أنكي العرب",
  decks: "الرزم",
  add: "إضافة",
  study: "دراسة",
  stats: "الإحصائيات",
  settings: "الإعدادات",
  import: "استيراد ذكي",
  newCards: "بطاقات جديدة",
  learning: "قيد التعلم",
  review: "مراجعة",
  due: "مستحق",
  front: "الوجه (السؤال)",
  back: "الظهر (الإجابة)",
  save: "حفظ",
  cancel: "إلغاء",
  delete: "حذف",
  again: "مجدداً",
  hard: "صعب",
  good: "جيد",
  easy: "سهل",
  showAnswer: "إظهار الإجابة",
  editCard: "تعديل البطاقة",
  emptyDeck: "لا توجد بطاقات مستحقة في هذه الرزمة حالياً. عمل رائع!",
  heatmap: "خريطة النشاط",
  accuracy: "معدل الدقة",
  totalCards: "إجمالي البطاقات",
  deckName: "اسم الرزمة",
  cardType: "نوع البطاقة",
  basicType: "أساسية (وجه/ظهر)",
  clozeType: "ملء الفراغات (Cloze)",
  clozeHint: "استخدم {{c1::نص}} لإضافة فراغ",
  importPdfTitle: "مساعد الاستيراد الذكي",
  importPdfDesc: "تحدث مع الذكاء الاصطناعي لاستخراج البطاقات من ملفاتك بدقة.",
  uploadPdf: "رفع ملف PDF",
  driveUrl: "رابط Google Drive",
  driveUrlPlaceholder: "رابط ملف PDF من Google Drive",
  dropFile: "اسحب ملف الجدول هنا",
  selectedFile: "الملف: {name}",
  processFile: "تحليل الجداول واستخراج الكلمات",
  analyzing: "جاري تحليل الجداول واستخراج كل كلمة ومعناها...",
  generating: "جاري تحويل البيانات إلى بطاقات...",
  reviewCards: "مراجعة الكلمات المستخرجة",
  addToDeck: "إضافة جميع الكلمات للرزمة",
  noCardsGenerated: "لم نتمكن من العثور على معلومات كافية. حاول تحديد صفحات معينة.",
  importSuccess: "تمت إضافة {count} بطاقة بنجاح!",
  invalidUrl: "الرابط غير صالح.",
  fileTooLarge: "الملف كبير جداً (أقصى حد 20 ميجابايت).",
  extractingTables: "جاري معالجة الصفوف والصفحات...",
  stageReading: "جاري قراءة الملف...",
  stageExtracting: "جاري استخراج البيانات...",
  stageGenerating: "جاري بناء البطاقات...",
  stageFinishing: "جاري الإنهاء...",
  estimatedTime: "المتبقي: {time} ثوانٍ",
  progressComplete: "اكتملت المعالجة!",
  chatWelcome: "مرحباً! أنا مساعدك الذكي. ارفع ملف PDF وأخبرني ماذا تريد أن تستخرج منه. يمكنك طلب صفحات معينة مثل 'استخرج الصفحة 1' أو 'الصفحات 2-5'.",
  chatInputPlaceholder: "اكتب طلبك هنا (مثلاً: استخرج الصفحة الأولى)...",
  confirmExtraction: "تم استقبال الملف بنجاح. أي الصفحات تود تحليلها؟",
  extractionSuccess: "تم استخراج {count} بطاقة بنجاح من {source}. يمكنك مراجعتها أدناه قبل الحفظ.",
  savingCards: "جاري حفظ البطاقات في الرزمة المختارة...",
  noFileUploaded: "يرجى رفع ملف PDF أولاً لكي أتمكن من مساعدتك.",
  // Notifications
  notifTitle: "تنبيهات المراجعة",
  notifEnabled: "تفعيل التنبيهات الذكية",
  notifPreferredTime: "وقت التذكير المفضل",
  notifDailyLimit: "الحد الأقصى للتنبيهات يومياً",
  notifMorning: "الصباح (8:00)",
  notifAfternoon: "الظهيرة (13:00)",
  notifEvening: "المساء (20:00)",
  notifMessageDue: "جاهز لمراجعة {count} بطاقة اليوم؟ افتح التطبيق وابدأ الآن!",
  notifMessageOverdue: "لديك بطاقات متأخرة للمراجعة! لا تضيع وقتك، راجعها الآن.",
  notifPermissionDenied: "يرجى تفعيل صلاحيات التنبيهات من إعدادات المتصفح.",
  notifSettingsSaved: "تم حفظ إعدادات التنبيهات بنجاح.",
  notifTest: "إرسال تنبيه تجريبي",
};
